
function vsi_dt_config(this_block)

  % Revision History:
  %
  %   09-Dec-2024  (18:57 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     D:\MarcosGomez\DCMG\vsi_dt.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('vsi_dt');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('d1');
  this_block.addSimulinkInport('d2');
  this_block.addSimulinkInport('d3');

  this_block.addSimulinkOutport('s1');
  this_block.addSimulinkOutport('s2');
  this_block.addSimulinkOutport('s3');
  this_block.addSimulinkOutport('s4');
  this_block.addSimulinkOutport('s5');
  this_block.addSimulinkOutport('s6');
  this_block.addSimulinkOutport('interrupt');

  s1_port = this_block.port('s1');
  s1_port.setType('UFix_1_0');
  s1_port.useHDLVector(false);
  s2_port = this_block.port('s2');
  s2_port.setType('UFix_1_0');
  s2_port.useHDLVector(false);
  s3_port = this_block.port('s3');
  s3_port.setType('UFix_1_0');
  s3_port.useHDLVector(false);
  s4_port = this_block.port('s4');
  s4_port.setType('UFix_1_0');
  s4_port.useHDLVector(false);
  s5_port = this_block.port('s5');
  s5_port.setType('UFix_1_0');
  s5_port.useHDLVector(false);
  s6_port = this_block.port('s6');
  s6_port.setType('UFix_1_0');
  s6_port.useHDLVector(false);
  interrupt_port = this_block.port('interrupt');
  interrupt_port.setType('UFix_1_0');
  interrupt_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('d1').width ~= 10);
      this_block.setError('Input data type for port "d1" must have width=10.');
    end

    if (this_block.port('d2').width ~= 10);
      this_block.setError('Input data type for port "d2" must have width=10.');
    end

    if (this_block.port('d3').width ~= 10);
      this_block.setError('Input data type for port "d3" must have width=10.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('vsi_dt.v');
  this_block.addFile('dead_time.v');
  this_block.addFile('pwm.v');
  this_block.addFile('pwm_deadtime.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

